server:
  port: 8085

spring:
  application:
    name: APIGATEWAY

  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/monalishaswain280/Microservice_Springboot
          clone-on-start: true
